import Header from './components/Header';
import Providers from './Providers';
import './globals.css';

export const metadata = {
  title: 'NextJS 13 IMDB App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
